### ISSUE TITLE
pdfjam uses `locale -k` which is not portable.

### ISSUE THREAD

**Issue by vext01** [rrthomas/pdfjam#29]
Hi,

pdfjam uses `locale -k` to try to guess the default paper size, however `locale -k` isn't portable.

On my OpenBSD system:
```
$ locale -k
locale: unknown option -- k
usage: locale [-a | -m | charmap]
```

If we drop `-k` then we get some locale-related stuff, but nothing to do with paper:
```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE=en_US.UTF-8
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_MESSAGES="C"
LC_ALL=
```

A quick fix is to skip guessing the paper size on OpenBSD, but I wonder if there's a better way?

Thanks

**Comment by DavidFirth** [comment]
Many thanks for reporting this.  I suppose the best fix might be one that is more general, i.e., to test first whether `locale -k` gives a suitable reply, and use it if so (but not otherwise).

This papersize guessing could alternatively be removed completely.  (It is a relatively recent addition to pdfjam, suggested by a user; but certainly **I** do not ever need my computer to guess the papersize that I want when I use pdfjam, and maybe nobody else really does, either?

**Comment by vext01** [comment]
Another option:

Auto-detecting paper is hard, but you could allow unified manual selection
with libpaper? There's a tool called 'paperconf' that you could use.
