### ISSUE TITLE
unknown keyword LC_PAPER

### ISSUE THREAD

**Issue by habere-et-dispertire** [rrthomas/pdfjam#48]
pdfjam 3.03 reports on the first line of output:

> unknown keyword LC_PAPER

This is perhaps a missing environment variable that is not set in MacTex Live 2021, running under macOS 10.13.6. This sounds like a portability issue. The code in questions appears to be:

`if command -v locale >/dev/null ; then
    paperheight=$(locale -k LC_PAPER | sed -e '1!d' -e 's/.*=//') ;`

I cannot find anything on how Tex interacts (if at all) with environment variables. Paper size is apparently extracted with `tlmg paper`, but that lists the default for a variety of binaries. If we only want to look at `pdftex` then we can extract that papersize with `tlmgr pdftex paper`

> Current pdftex paper size (from /usr/local/texlive/2021/texmf-config/tex/generic/tex-ini-files/pdftexconfig.tex): a4

FYI, `/etc/papersize` does not appear to exist on macOS.

**Comment by euphemism** [comment]
Hey there, did you ever figure out how to get around this error?

**Comment by habere-et-dispertire** [comment]
Sorry, but this still persists. If I add to my bash profile:

~~~bash
export LC_PAPER=a4
~~~

And then `source` it, then I see:

~~~bash
$ printenv | grep LC

LC_PAPER=a4
LC_CTYPE=UTF-8
~~~

And `pdfjam`  still issues the same error:

~~~
unknown keyword LC_PAPER
~~~

I tried uppercase `A4` too, but that gives the same result. `Tex Live Utility` reports that the paper size for all Tex programs is already set to `A4`.

I'm not sure what to try next. I created `/etc/papersize` and tried setting it to both `a4` and `A4` but neither produced a change.

**Comment by habere-et-dispertire** [comment]
Thank you for all the help! :) I have no problem using `pdfjam`, so I'll close this as this appears to be a local(e) issue.

You are right that the error seems to come from `locale -k LC_PAPER`.

`export LC_PAPER=en_GB` is seen by `printenv`, but is not listed with `locale`. My odd system I guess.

Thanks again.

**Comment by ryofurue** [comment]
Sorry if I'm missing something, but the error comes from the line
```sh
    paperheight=$(locale -k LC_PAPER . . .
```
in `/Library/TeX/texbin/pdfjam`.  If I understand the issue correctly, macOS doesn't define LC_PAPER, so that you shouldn't ask for its value.

The above command needs a logic like: `if not macOS, then locale -k LC_PAPER . . .`

Since LC_PAPER is a GNU extension (https://man7.org/linux/man-pages/man5/locale.5.html ), this cannot be regarded as a bug on the part of macOS.

**Comment by rrthomas** [comment]
Thanks for this point, @ryofurue. I should have realized this wasn't portable myself, as I'm the author of libpaper 2, which has support for `LC_PAPER` (or at least the underlying GNU libc feature).

I have taken the opportunity to overhaul the support for paper sizes in `pdfjam`. Instead of `locale`, I use libpaper 2 if installed. This allows a much wider range of paper sizes to be configured (including user-defined sizes), and will fall back to the locale default size where available.

I also added support for the much wider range of paper sizes supported by `geometry` version 5 and later (since 2010!), so you can now say, for example, `--ansiapaper`. `geometry` is now required; this seems reasonable, as it's been a pretty core package for a long time now.

Finally, I updated the links to alternative packages, adding both the excellent PDFtk, and my own PSPDFUtils (aka PSUtils version 3, which now supports PDF).

Since these changes are quite significant, I'll allow a bit of time before making a new release.

**Comment by ryofurue** [comment]
Wow!  Thank you for your your extensive response!  Looking forward to those new features, as I have been long wanting to specify a default paper size.

**Comment by rrthomas** [comment]
You're welcome! I'll wait a few more days, and then if I get no further feedback, make a release.

**Comment by rrthomas** [comment]
I've released 3.05.

**Comment by ryofurue** [comment]
> I've released 3.05.

I wonder how each new version is propagated?  I'm not at all familiar with how these things work.

I think I've gotten `pdfjam` through `texlive`, and I regularly update `texlive` via `sudo tlmgr update --self --all`, which I think installs new versions of packages from CTAN.

**Comment by rrthomas** [comment]
Apologies, I forgot to make the release on CTAN (I only released on GItHub). I have now submitted the release to CTAN; expect it to be available in 24–48 hours.

**Comment by ryofurue** [comment]
> Apologies,

Sorry. I didn't mean to push you. No apologies are necessary.

> I have now submitted the release to CTAN

Thanks!  I confirm that the latest upgrade of `texlive` brought in the latest version of `pdfjam` (3.05).

After installing  the `libpaper` package, I'm now able to change the default paper size by setting the env. var. `PAPERSIZE`.  So, everything works now.

I suggest that a documentation (perhaps `pdfjam --help`) recommend `libpaper`.  I noticed `libpaper` only 1) because you mentioned `libpaper` above and 2) because I read the source code of `pdfjam`. Ordinary users wouldn't realize this.

**Comment by rrthomas** [comment]
Thanks for your further suggestions. I don't think ordinary users would be able to install a C library from source, unfortunately; I hope TeXLive will upgrade libpaper to version 2 in due course. libpaper is mentioned in `README.md`, a typical place that users building a package from source will look to find dependencies.

**Comment by ryofurue** [comment]
>  I don't think ordinary users would be able to install a C library from source,

Is that the norm for libpaper?  Most libraries are available in the form of a package. On Mac, you install libpaper with `brew install libpaper`. On Ubuntu Linux and Debian Linux, I guess you would do `aptitude install libpaper`.  And so on and so forth.

In any case, on mac, it's as easy to install libpaper as to install texlive, both just a matter of a single command.

**Comment by rrthomas** [comment]
> > I don't think ordinary users would be able to install a C library from source,
> 
> Is that the norm for libpaper? Most libraries are available in the form of a package. On Mac, you install libpaper with `brew install libpaper`. On Ubuntu Linux and Debian Linux, I guess you would do `aptitude install libpaper`. And so on and so forth.

Sure, and when packaged, pdfjam should depend on libpaper so that the latter is installed automatically.

**Comment by ryofurue** [comment]
> Sure, and when packaged, pdfjam should depend on libpaper so that the latter is installed automatically.

That means, I guess, that `texlive` should include `libpaper` because it's supposed to be self-contained?  (If I'm not mistaken, I get `pdfjam` as part of `texlive`. I don't think I have separately installed `pdfjam`.)

Perhaps I should notify the packager of `texlive`?

**Comment by rrthomas** [comment]
> That means, I guess, that `texlive` should include `libpaper` because it's supposed to be self-contained? (If I'm not mistaken, I get `pdfjam` as part of `texlive`. I don't think I have separately installed `pdfjam`.)

Exactly, ideally libpaper v2 would come with texlive (currently it ships v1, which does not work with pdfjam, but v2 is backwards-compatible with v1).
> 
> Perhaps I should notify the packager of `texlive`?

**Comment by ryofurue** [comment]
> . . .  ideally libpaper v2 would come with texlive (currently it ships v1, . . .

I'm surprised. I must be missing something. I've searched the texlive installation on my Macs but haven't found `libpaper` or the `paper` command. The `MacTeX` project ( https://www.tug.org/mactex/ ) claims that their package contains the entirety of `texlive` . . . ( I do find the `pdfjam` command in there and it's the latest version, 3.06, because I update the entire `texlive` installation using the `tlmgr` command.)

Anyway, I'll try to locate the right issue tracker (github or something) of `texlive` and gently ask them to include the latest `paper` command (in the `libpaper` suite) in order for the latest `pdfjam` command to be able to select the right default paper size.

**Comment by rrthomas** [comment]
> I'm surprised. I must be missing something. I've searched the texlive installation on my Macs but haven't found `libpaper` or the `paper` command.

I base my assertion that texlive has libpaper on the fact that it's in the source repo. I use texlive myself as packaged in Debian, which packages libpaper separately.

libpaper v1 does not have the `paper` command; that's precisely why pdfjam requires v2.

> Anyway, I'll try to locate the right issue tracker (github or something) of `texlive` and gently ask them to include the latest `paper` command (in the `libpaper` suite) in order for the latest `pdfjam` command to be able to select the right default paper size.

Thanks!
