### ISSUE TITLE
NEW MAINTAINER WANTED

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/pdfjam#74]
I no longer have time to give pdfjam the time it needs (and I maintain a competitor/alternative-for-many-uses, PDFPSUtils).

Therefore it would be great if someone else could take over the project.

I will do my best to merge fixes and make new releases as required, but I won't be able to investigate bug reports myself. Again, patches for existing issues are very much welcome!

**Comment by mgkurtz** [comment]
I think I can co-maintain pdfjam for now, if this is in your interest. If this works well, I can also take over maintenance.

The bash code seems simple enough, so I can take a closer look at some open issues and fix a few bugs. Some of the open issues could simply be closed for being fixed by now.

Additionally, I would try to setup a regression test suite using the examples from `README.md` and `Testing.md` and some funny `l3build` configuration for comparing pdf outputs. Although `l3build` is intended for different work, it should be flexible enough to have the tests execute `bash` on `test1.sh` instead of `pdflatex` on `test1.pvt`. Having a proper test suite will be a big help in further maintenance.

**Comment by rrthomas** [comment]
@mgkurtz, I would be delighted with that. @DavidFirth, I would be happy to handle this by continuing to make the next few CTAN releases, allowing @mgkurtz to handle things on GitHub, if that's OK with you?

**Comment by DavidFirth** [comment]
@mgkurtz @rrthomas  This looks like very good news.  Thanks for asking me, but really there is no need: my ability to contribute anything meaningful to pdfjam ended long ago!  And it is definitely not proprietary software.

**Comment by rrthomas** [comment]
@mgkurtz thanks, I've added you as a collaborator, and will close this issue for now.
